### ISSUE TITLE
what about feedback service ? 

### ISSUE THREAD

**Issue by elabda3company** [M2mobi/ApnsPHP#29]
what about feedback service ? 
**should we use the same service for sending ?** 

```php
$feedback = new ApnsPHP_Feedback(
        ApnsPHP_Abstract::ENVIRONMENT_PRODUCTION,
        'AuthKey_H24J4T2PJ7.p8',
        ApnsPHP_Abstract::PROTOCOL_HTTP
    );

// Connect to the Apple Push Notification Service
    // $push->setTeamId('TWYX27B7ZY');
    // $push->setKeyId('H24J4T2PJ7');
// Set the write interval to null for the HTTP/2 Protocol.
    // $push->setWriteInterval(0);

// Connect to the Apple Push Notification Feedback Service
$feedback->connect();

$aDeviceTokens = $feedback->receive();
if (!empty($aDeviceTokens)) {
	var_dump($aDeviceTokens);
}
```

**Comment by SMillerDev** [comment]
There is no such thing as the HTTP feedback service. See https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH13-SW12 this is classified as legacy by apple. All the information you get is the information you get directly.

**Comment by elabda3company** [comment]
Thank You
